namespace BlazorMovie.Models.Providers
{
    public class ProviderResults
    {
        public AD? AD { get; set; }
        public AE? AE { get; set; }
        public AL? AL { get; set; }
        public AR? AR { get; set; }
        public AT? AT { get; set; }
        public AU? AU { get; set; }
        public BA? BA { get; set; }
        public BE? BE { get; set; }
        public BG? BG { get; set; }
        public BO? BO { get; set; }
        public BR? BR { get; set; }
        public BZ? BZ { get; set; }
        public CA? CA { get; set; }
        public CH? CH { get; set; }
        public CL? CL { get; set; }
        public CO? CO { get; set; }
        public CR? CR { get; set; }
        public CY? CY { get; set; }
        public CZ? CZ { get; set; }
        public DE? DE { get; set; }
        public DK? DK { get; set; }
        public DO? DO { get; set; }
        public EC? EC { get; set; }
        public EE? EE { get; set; }
        public EG? EG { get; set; }
        public ES? ES { get; set; }
        public FI? FI { get; set; }
        public FR? FR { get; set; }
        public GB? GB { get; set; }
        public GR? GR { get; set; }
        public GT? GT { get; set; }
        public HK? HK { get; set; }
        public HN? HN { get; set; }
        public HR? HR { get; set; }
        public HU? HU { get; set; }
        public ID? ID { get; set; }
        public IE? IE { get; set; }
        public IL? IL { get; set; }
        public IN? IN { get; set; }
        public IS? IS { get; set; }
        public IT? IT { get; set; }
        public JM? JM { get; set; }
        public JP? JP { get; set; }
        public KR? KR { get; set; }
        public LC? LC { get; set; }
        public LI? LI { get; set; }
        public LT? LT { get; set; }
        public LU? LU { get; set; }
        public LV? LV { get; set; }
        public ME? ME { get; set; }
        public MK? MK { get; set; }
        public MT? MT { get; set; }
        public MX? MX { get; set; }
        public MY? MY { get; set; }
        public NI? NI { get; set; }
        public NL? NL { get; set; }
        public NO? NO { get; set; }
        public NZ? NZ { get; set; }
        public PA? PA { get; set; }
        public PE? PE { get; set; }
        public PH? PH { get; set; }
        public PL? PL { get; set; }
        public PT? PT { get; set; }
        public PY? PY { get; set; }
        public RO? RO { get; set; }
        public RS? RS { get; set; }
        public RU? RU { get; set; }
        public SA? SA { get; set; }
        public SE? SE { get; set; }
        public SG? SG { get; set; }
        public SI? SI { get; set; }
        public SK? SK { get; set; }
        public SM? SM { get; set; }
        public SV? SV { get; set; }
        public TH? TH { get; set; }
        public TR? TR { get; set; }
        public TT? TT { get; set; }
        public TW? TW { get; set; }
        public UA? UA { get; set; }
        public US? US { get; set; }
        public UY? UY { get; set; }
        public VE? VE { get; set; }
        public ZA? ZA { get; set; }
    }
}

